// Code generated by schemas/generate_go.py. DO NOT EDIT.

package protocol

import "time"

type AgentConfig struct {
	AssignedModels     []string `json:"assigned_models"`
	BenchMode          bool     `json:"bench_mode"`
	HeartbeatIntervalS float64  `json:"heartbeat_interval_s"`
	IdleThresholdS     float64  `json:"idle_threshold_s"`
	PollIntervalMs     int      `json:"poll_interval_ms"`
	VRAMEvictAfterS    float64  `json:"vram_evict_after_s"`
}

type AgentEvent struct {
	AgentID string            `json:"agent_id"`
	At      time.Time         `json:"at"`
	Detail  map[string]string `json:"detail"`
	Kind    EventKind         `json:"kind"`
}

type AgentSnapshot struct {
	AgentID        string          `json:"agent_id"`
	Caps           DeviceCaps      `json:"caps"`
	GPUs           []GpuStatus     `json:"gpus"`
	Host           string          `json:"host"`
	MemAvailableMB int             `json:"mem_available_mb"`
	Replicas       []ReplicaStatus `json:"replicas"`
	State          AgentState      `json:"state"`
	Suspect        bool            `json:"suspect"`
	UserIdleS      float64         `json:"user_idle_s"`
}

type AgentState string

const (
	AgentStateIdle     AgentState = "idle"
	AgentStateActive   AgentState = "active"
	AgentStateDraining AgentState = "draining"
)

type DeviceCaps struct {
	AgentVersion string    `json:"agent_version"`
	CPUCores     int       `json:"cpu_cores"`
	CPUModel     string    `json:"cpu_model"`
	DiskFreeMB   int       `json:"disk_free_mb"`
	GPUs         []GpuInfo `json:"gpus"`
	Hostname     string    `json:"hostname"`
	Os           OsFamily  `json:"os"`
	OsVersion    string    `json:"os_version"`
	RAMMB        int       `json:"ram_mb"`
}

type EventKind string

const (
	EventKindUserReturned     EventKind = "user_returned"
	EventKindUserIdle         EventKind = "user_idle"
	EventKindReplicaReady     EventKind = "replica_ready"
	EventKindReplicaSuspended EventKind = "replica_suspended"
	EventKindReplicaResumed   EventKind = "replica_resumed"
	EventKindReplicaStopped   EventKind = "replica_stopped"
	EventKindAgentStarting    EventKind = "agent_starting"
	EventKindAgentStopping    EventKind = "agent_stopping"
)

type GpuInfo struct {
	Index  int    `json:"index"`
	Name   string `json:"name"`
	Vendor string `json:"vendor"`
	VRAMMB int    `json:"vram_mb"`
}

type GpuStatus struct {
	Index       int      `json:"index"`
	PowerW      *float64 `json:"power_w"`
	TempC       *float64 `json:"temp_c"`
	UtilPercent float64  `json:"util_percent"`
	VRAMFreeMB  int      `json:"vram_free_mb"`
}

type Heartbeat struct {
	AgentID         string          `json:"agent_id"`
	CPUPercent      float64         `json:"cpu_percent"`
	GPUs            []GpuStatus     `json:"gpus"`
	LeaseIDs        []string        `json:"lease_ids"`
	LoadAvg         *float64        `json:"load_avg"`
	MemAvailableMB  int             `json:"mem_available_mb"`
	ProtocolVersion int             `json:"protocol_version"`
	Replicas        []ReplicaStatus `json:"replicas"`
	SentAt          time.Time       `json:"sent_at"`
	Seq             int             `json:"seq"`
	State           AgentState      `json:"state"`
	TempCPUC        *float64        `json:"temp_cpu_c"`
	UserIdleS       float64         `json:"user_idle_s"`
}

type HeartbeatResponse struct {
	Config          *AgentConfig `json:"config"`
	DesiredModels   []string     `json:"desired_models"`
	RevokedLeaseIDs []string     `json:"revoked_lease_ids"`
}

type JobState string

const (
	JobStatePending   JobState = "pending"
	JobStateRunning   JobState = "running"
	JobStateDone      JobState = "done"
	JobStateCancelled JobState = "cancelled"
)

type JobStatus struct {
	DeadUnits  int      `json:"dead_units"`
	DoneUnits  int      `json:"done_units"`
	JobID      string   `json:"job_id"`
	State      JobState `json:"state"`
	TotalUnits int      `json:"total_units"`
}

type JobSubmit struct {
	Kind       WorkerKind        `json:"kind"`
	ModelID    string            `json:"model_id"`
	Params     map[string]string `json:"params"`
	PayloadRef string            `json:"payload_ref"`
	Priority   int               `json:"priority"`
}

type ModelManifest struct {
	ChatTemplateHint *string    `json:"chat_template_hint"`
	DefaultArgs      []string   `json:"default_args"`
	Family           string     `json:"family"`
	FileName         string     `json:"file_name"`
	License          *string    `json:"license"`
	MinRAMMB         int        `json:"min_ram_mb"`
	MinVRAMMB        int        `json:"min_vram_mb"`
	ModelID          string     `json:"model_id"`
	Quant            string     `json:"quant"`
	SHA256           string     `json:"sha256"`
	SizeBytes        int        `json:"size_bytes"`
	SourceURL        *string    `json:"source_url"`
	WorkerKind       WorkerKind `json:"worker_kind"`
}

type ModelRequirements struct {
	MinRAMMB   int        `json:"min_ram_mb"`
	MinVRAMMB  int        `json:"min_vram_mb"`
	ModelID    string     `json:"model_id"`
	NeedsGPU   bool       `json:"needs_gpu"`
	WorkerKind WorkerKind `json:"worker_kind"`
}

type OsFamily string

const (
	OsFamilyWindows OsFamily = "windows"
	OsFamilyMacos   OsFamily = "macos"
	OsFamilyLinux   OsFamily = "linux"
)

type RegisterRequest struct {
	Caps            DeviceCaps `json:"caps"`
	EnrollmentToken string     `json:"enrollment_token"`
	ProtocolVersion int        `json:"protocol_version"`
}

type RegisterResponse struct {
	AgentID     string      `json:"agent_id"`
	Config      AgentConfig `json:"config"`
	DeviceToken string      `json:"device_token"`
}

type ReplicaEndpoint struct {
	AgentID  string `json:"agent_id"`
	Host     string `json:"host"`
	Inflight int    `json:"inflight"`
	ModelID  string `json:"model_id"`
	Port     int    `json:"port"`
}

type ReplicaState string

const (
	ReplicaStateLoading   ReplicaState = "loading"
	ReplicaStateReady     ReplicaState = "ready"
	ReplicaStateSuspended ReplicaState = "suspended"
	ReplicaStateStopped   ReplicaState = "stopped"
)

type ReplicaStatus struct {
	GPU      bool         `json:"gpu"`
	Inflight int          `json:"inflight"`
	ModelID  string       `json:"model_id"`
	Port     int          `json:"port"`
	State    ReplicaState `json:"state"`
}

type UnitTransition struct {
	AgentID    string        `json:"agent_id"`
	At         time.Time     `json:"at"`
	Attempt    int           `json:"attempt"`
	JobID      string        `json:"job_id"`
	State      WorkUnitState `json:"state"`
	WorkUnitID string        `json:"work_unit_id"`
}

type WorkMetrics struct {
	DurationS float64 `json:"duration_s"`
	Items     *int    `json:"items"`
	Tokens    *int    `json:"tokens"`
}

type WorkResult struct {
	Error      *string          `json:"error"`
	Metrics    *WorkMetrics     `json:"metrics"`
	ResultRef  *string          `json:"result_ref"`
	Status     WorkResultStatus `json:"status"`
	WorkUnitID string           `json:"work_unit_id"`
}

type WorkResultStatus string

const (
	WorkResultStatusSucceeded WorkResultStatus = "succeeded"
	WorkResultStatusFailed    WorkResultStatus = "failed"
)

type WorkUnitLease struct {
	Attempt      int        `json:"attempt"`
	EstDurationS *float64   `json:"est_duration_s"`
	InputURL     string     `json:"input_url"`
	JobID        string     `json:"job_id"`
	Kind         WorkerKind `json:"kind"`
	LeaseExpires time.Time  `json:"lease_expires"`
	ModelID      string     `json:"model_id"`
	WorkUnitID   string     `json:"work_unit_id"`
}

type WorkUnitSpec struct {
	EstDurationS *float64 `json:"est_duration_s"`
	Idx          int      `json:"idx"`
	InputRef     string   `json:"input_ref"`
	WorkUnitID   string   `json:"work_unit_id"`
}

type WorkUnitState string

const (
	WorkUnitStatePending WorkUnitState = "pending"
	WorkUnitStateLeased  WorkUnitState = "leased"
	WorkUnitStateDone    WorkUnitState = "done"
	WorkUnitStateDead    WorkUnitState = "dead"
)

type WorkerKind string

const (
	WorkerKindChat       WorkerKind = "chat"
	WorkerKindEmbed      WorkerKind = "embed"
	WorkerKindTranscribe WorkerKind = "transcribe"
)
