"""Generate Go wire types from the committed Fallow JSON Schemas."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

Schema = dict[str, Any]

ACRONYMS = {
    "cpu": "CPU",
    "gpu": "GPU",
    "gpus": "GPUs",
    "id": "ID",
    "ids": "IDs",
    "json": "JSON",
    "mb": "MB",
    "ram": "RAM",
    "sha256": "SHA256",
    "url": "URL",
    "vram": "VRAM",
}


class GenerationError(ValueError):
    """The schema uses a construct this generator does not support."""


def go_name(value: str) -> str:
    """Convert a snake-case JSON name to an exported Go identifier."""
    return "".join(ACRONYMS.get(part.lower(), part.capitalize()) for part in value.split("_"))


def ref_name(ref: str) -> str:
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        raise GenerationError(f"unsupported reference: {ref}")
    return ref.removeprefix(prefix)


def go_type(schema: Schema) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])

    if "anyOf" in schema:
        choices = schema["anyOf"]
        non_null = [choice for choice in choices if choice.get("type") != "null"]
        if len(choices) != 2 or len(non_null) != 1:
            raise GenerationError(f"unsupported anyOf: {choices!r}")
        return "*" + go_type(non_null[0])

    kind = schema.get("type")
    if kind == "string":
        return "time.Time" if schema.get("format") == "date-time" else "string"
    if kind == "integer":
        return "int"
    if kind == "number":
        return "float64"
    if kind == "boolean":
        return "bool"
    if kind == "array":
        return "[]" + go_type(schema["items"])
    if kind == "object" and isinstance(schema.get("additionalProperties"), dict):
        return "map[string]" + go_type(schema["additionalProperties"])

    raise GenerationError(f"unsupported schema type: {schema!r}")


def collect_types(schema_dir: Path) -> dict[str, Schema]:
    types: dict[str, Schema] = {}
    for path in sorted(schema_dir.glob("*.json")):
        schema = json.loads(path.read_text())
        named = {schema["title"]: schema, **schema.get("$defs", {})}
        for name, definition in named.items():
            definition = {key: value for key, value in definition.items() if key != "$defs"}
            previous = types.get(name)
            if previous is not None and previous != definition:
                raise GenerationError(f"conflicting definitions for {name} in {path}")
            types[name] = definition
    return types


def render_enum(name: str, schema: Schema) -> list[str]:
    lines = [f"type {name} string", "", "const ("]
    for value in schema["enum"]:
        constant = name + go_name(value)
        lines.append(f'\t{constant} {name} = "{value}"')
    lines.extend([")", ""])
    return lines


def render_struct(name: str, schema: Schema) -> list[str]:
    lines = [f"type {name} struct {{"]
    for json_name, field in schema.get("properties", {}).items():
        lines.append(f'\t{go_name(json_name)} {go_type(field)} `json:"{json_name}"`')
    lines.extend(["}", ""])
    return lines


def generate(schema_dir: Path) -> str:
    lines = [
        "// Code generated by schemas/generate_go.py. DO NOT EDIT.",
        "",
        "package protocol",
        "",
        'import "time"',
        "",
    ]
    for name, schema in sorted(collect_types(schema_dir).items()):
        if schema.get("type") == "string" and "enum" in schema:
            lines.extend(render_enum(name, schema))
        elif schema.get("type") == "object" and "properties" in schema:
            lines.extend(render_struct(name, schema))
        else:
            raise GenerationError(f"{name} is neither an enum nor an object schema")
    source = "\n".join(lines)
    try:
        formatted = subprocess.run(
            ["gofmt"],
            input=source,
            text=True,
            capture_output=True,
            check=True,
        )
    except FileNotFoundError as exc:
        raise GenerationError("gofmt is required to generate Go wire types") from exc
    except subprocess.CalledProcessError as exc:
        raise GenerationError(f"gofmt failed: {exc.stderr.strip()}") from exc
    return formatted.stdout


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schemas", type=Path, default=Path("schemas"))
    parser.add_argument("--output", type=Path, default=Path("go-agent/protocol/types_gen.go"))
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    rendered = generate(args.schemas)
    if args.check:
        if not args.output.exists() or args.output.read_text() != rendered:
            print(f"generated Go types are stale: {args.output}", file=sys.stderr)
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
